### ISSUE TITLE
Runtime Issue - Questions about deployments

### ISSUE THREAD

**Issue by vpasquier** [gsuitedevs/gmail-add-ons-samples#37]
Hello!

I'm trying to build my custom addon with some third party libraries as well. I have followed all the steps pretty well (thank you again for this sample very interesting!).

Unfortunately, when running the addon in my Gmail, google executes the `gulp.js` :/

Hence my questions:
- What do we really need to clasp push ? Does google is installing all the nodes modules and running gulp on its side before executing it or do we need to push the folder `node_modules` and the result of the `npm run build` ?
- I tried to do the second point but:
  - When I open the app script console, I see no file that have been pushed (and actually its like its skipping the push completely with there is too many files)
  - When I run `npm run build` locally, I have no `dist` folder created (but there is no error).

I'm kind of confused as you can see on the deployment, execution in general of google app script when using third party libraries. Would you be ok to help me on this?

Thank you very much!

**Comment by sqrrrl** [comment]
Running clasp push should only push the dist & src dirs. The .claspignore file excludes node_modules and a bunch of other things like gulpfile.js

Just tried with a clean install of clasp and worked as expected with meeting assistant.

Build:

➜  meeting-assistant git:(master) ✗ npm run build

> meeting-assistant@1.0.0 build /Users/sbazyl/gsuitedevs/gmail-add-ons-samples/meeting-assistant
> gulp
[15:38:29] Using gulpfile ~/gsuitedevs/gmail-add-ons-samples/meeting-assistant/gulpfile.js
[15:38:29] Starting 'concat-third-party'...
[15:38:29] Finished 'concat-third-party' after 74 ms
[15:38:29] Starting 'default'...
[15:38:29] Finished 'default' after 20 μs

meeting-assistant git:(master) ✗ clasp create "MA test"        
? Clone which script? standalone
Created new standalone script: https://script.google.com/d/<redacted>/edit

Pushing files:

➜  meeting-assistant git:(master) ✗ clasp push
? Manifest file has been updated. Do you want to push and overwrite? Yes
└─ appsscript.json
└─ dist/3p-bundle.js
└─ src/ActionHandlers.js
└─ src/DeadlineMonitor.js
└─ src/Main.js
└─ src/MessageUtils.js
└─ src/Scheduler.js
└─ src/Settings.js
└─ src/TimePeriod.js
└─ src/Views.js
Pushed 10 files.

Could you capture (and sanitize anything sensitive) a console session where you go through the steps you're doing? Not sure what the issue is without additional details.

**Comment by vpasquier** [comment]
Thank you very much for your help! I've just missed the third party folder high in hierarchy.
